name: Main Pipeline

on:
  push: {}

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

jobs:
  buildAndPublish:
    name: Build the app and publish to itch.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Getting cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library

      # https://github.com/webbertakken/unity-builder/issues/183#issuecomment-735933455
      - name: Build project
        uses: webbertakken/unity-builder@v2.0-alpha
        with:
          unityVersion: 2019.4.14f1
          targetPlatform: WebGL

      - name: Upload artifacts (test)
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

      - name: Deploy project
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: Web
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: build/WebGL
